import { useState, useEffect } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { 
  TrendingUp, 
  Users, 
  Globe, 
  Zap,
  Award,
  ArrowUpRight,
  Star
} from "lucide-react";

export default function SuccessShowcase() {
  const [activeCase, setActiveCase] = useState(0);

  const successStories = [
    {
      company: "HydroTech Solutions",
      industry: "CleanTech",
      stage: "Series A",
      funding: "$3.2M",
      growth: "+340%",
      timeline: "8 months",
      description: "Water purification startup that secured Series A funding after using AI-generated business plan",
      metrics: [
        { label: "Revenue Growth", value: "340%", icon: TrendingUp },
        { label: "Team Size", value: "23", icon: Users },
        { label: "Markets", value: "7", icon: Globe }
      ],
      quote: "MyStartup.ai's business plan was instrumental in securing our Series A. The financial projections were spot-on.",
      founder: "Sarah Chen, CEO"
    },
    {
      company: "NeuroLink AI",
      industry: "Healthcare",
      stage: "Seed",
      funding: "$1.8M",
      growth: "+280%",
      timeline: "6 months",
      description: "AI-powered diagnostics platform that raised seed funding using generated pitch deck",
      metrics: [
        { label: "Patient Impact", value: "15K+", icon: Users },
        { label: "Accuracy Rate", value: "94%", icon: Award },
        { label: "Partnerships", value: "12", icon: Globe }
      ],
      quote: "The pitch deck generated by the platform perfectly captured our vision. Investors loved it.",
      founder: "Dr. Michael Rodriguez, Founder"
    },
    {
      company: "BlockChain Fintech",
      industry: "Web3",
      stage: "Pre-Seed",
      funding: "$850K",
      growth: "+450%",
      timeline: "4 months",
      description: "DeFi protocol that leveraged AI analysis to validate market opportunity",
      metrics: [
        { label: "TVL Growth", value: "450%", icon: TrendingUp },
        { label: "Active Users", value: "8.2K", icon: Users },
        { label: "Token Value", value: "+120%", icon: Zap }
      ],
      quote: "The Web3 market analysis was incredibly detailed. It helped us position perfectly in the DeFi space.",
      founder: "Alex Thompson, Co-founder"
    }
  ];

  useEffect(() => {
    const interval = setInterval(() => {
      setActiveCase((prev) => (prev + 1) % successStories.length);
    }, 5000);

    return () => clearInterval(interval);
  }, []);

  const currentStory = successStories[activeCase];

  return (
    <section className="py-20 bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900 relative overflow-hidden">
      {/* Background effects */}
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_50%,rgba(59,130,246,0.1),transparent_50%)]"></div>
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(16,185,129,0.1),transparent_50%)]"></div>
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative">
        <div className="text-center mb-16">
          <Badge className="bg-gradient-to-r from-blue-500 to-emerald-500 text-white mb-6">
            <Star className="w-4 h-4 mr-2" />
            Success Stories
          </Badge>
          
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
            Real Startups, Real Results
          </h2>
          <p className="text-xl text-blue-100 max-w-3xl mx-auto">
            From idea to funding - see how founders used our AI platform to build successful companies
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-12 items-center">
          {/* Story Content */}
          <div className="space-y-8">
            <Card className="bg-white/10 backdrop-blur-sm border-white/20 text-white">
              <CardContent className="p-8">
                <div className="flex items-center justify-between mb-6">
                  <div>
                    <h3 className="text-2xl font-bold mb-2">{currentStory.company}</h3>
                    <div className="flex items-center space-x-3">
                      <Badge variant="outline" className="border-white/30 text-white">
                        {currentStory.industry}
                      </Badge>
                      <Badge variant="outline" className="border-emerald-400/30 text-emerald-300">
                        {currentStory.stage}
                      </Badge>
                    </div>
                  </div>
                  <div className="text-right">
                    <div className="text-3xl font-bold text-emerald-400">{currentStory.funding}</div>
                    <div className="text-sm text-blue-200">Raised in {currentStory.timeline}</div>
                  </div>
                </div>

                <p className="text-blue-100 mb-6 leading-relaxed">
                  {currentStory.description}
                </p>

                <div className="grid grid-cols-3 gap-4 mb-6">
                  {currentStory.metrics.map((metric, index) => (
                    <div key={index} className="text-center p-4 bg-white/5 rounded-lg border border-white/10">
                      <metric.icon className="w-6 h-6 text-blue-400 mx-auto mb-2" />
                      <div className="text-xl font-bold text-white">{metric.value}</div>
                      <div className="text-xs text-blue-200">{metric.label}</div>
                    </div>
                  ))}
                </div>

                <blockquote className="border-l-4 border-blue-400 pl-4 mb-4">
                  <p className="text-blue-100 italic">"{currentStory.quote}"</p>
                  <footer className="text-blue-300 text-sm mt-2">— {currentStory.founder}</footer>
                </blockquote>
              </CardContent>
            </Card>

            {/* Story Navigation */}
            <div className="flex items-center justify-center space-x-4">
              {successStories.map((_, index) => (
                <button
                  key={index}
                  onClick={() => setActiveCase(index)}
                  className={`w-12 h-3 rounded-full transition-all duration-300 ${
                    index === activeCase 
                      ? 'bg-gradient-to-r from-blue-500 to-emerald-500' 
                      : 'bg-white/20 hover:bg-white/30'
                  }`}
                />
              ))}
            </div>
          </div>

          {/* Visual Dashboard */}
          <div className="relative">
            <Card className="bg-white rounded-2xl shadow-2xl overflow-hidden">
              <div className="bg-gradient-to-r from-blue-600 to-emerald-500 p-6 text-white">
                <h4 className="text-xl font-bold mb-2">Growth Analytics Dashboard</h4>
                <p className="text-blue-100 text-sm">Real-time performance metrics</p>
              </div>
              
              <CardContent className="p-6 space-y-6">
                {/* Growth Chart */}
                <div className="space-y-4">
                  <div className="flex justify-between items-center">
                    <span className="text-slate-600 font-medium">Revenue Growth</span>
                    <span className="text-emerald-600 font-bold">{currentStory.growth}</span>
                  </div>
                  <div className="h-3 bg-slate-200 rounded-full overflow-hidden">
                    <div 
                      className="h-full bg-gradient-to-r from-blue-500 to-emerald-500 rounded-full transition-all duration-1000"
                      style={{ width: `${parseInt(currentStory.growth)}%` }}
                    ></div>
                  </div>
                </div>

                {/* Key Metrics */}
                <div className="grid grid-cols-2 gap-4">
                  <div className="bg-blue-50 p-4 rounded-lg">
                    <div className="text-blue-600 text-sm font-medium">Funding Raised</div>
                    <div className="text-slate-900 text-xl font-bold">{currentStory.funding}</div>
                  </div>
                  <div className="bg-emerald-50 p-4 rounded-lg">
                    <div className="text-emerald-600 text-sm font-medium">Time to Fund</div>
                    <div className="text-slate-900 text-xl font-bold">{currentStory.timeline}</div>
                  </div>
                </div>

                {/* Industry Performance */}
                <div className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="text-slate-600">Industry Benchmark</span>
                    <span className="text-slate-400">vs. Market Average</span>
                  </div>
                  <div className="space-y-2">
                    <div className="flex justify-between items-center">
                      <span className="text-xs text-slate-500">Market Validation</span>
                      <div className="flex items-center space-x-2">
                        <div className="w-16 h-1 bg-slate-200 rounded">
                          <div className="w-full h-full bg-emerald-500 rounded"></div>
                        </div>
                        <span className="text-xs text-emerald-600 font-medium">Superior</span>
                      </div>
                    </div>
                    <div className="flex justify-between items-center">
                      <span className="text-xs text-slate-500">Investor Interest</span>
                      <div className="flex items-center space-x-2">
                        <div className="w-16 h-1 bg-slate-200 rounded">
                          <div className="w-5/6 h-full bg-blue-500 rounded"></div>
                        </div>
                        <span className="text-xs text-blue-600 font-medium">High</span>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Floating elements */}
            <div className="absolute -top-4 -right-4 w-20 h-20 bg-gradient-to-r from-emerald-400 to-blue-500 rounded-full flex items-center justify-center animate-bounce">
              <ArrowUpRight className="w-8 h-8 text-white" />
            </div>
          </div>
        </div>

        {/* Call to Action */}
        <div className="text-center mt-16">
          <Button 
            size="lg" 
            className="bg-gradient-to-r from-emerald-500 to-blue-600 hover:from-emerald-600 hover:to-blue-700 text-white text-lg px-8 py-6"
          >
            Start Your Success Story
            <ArrowUpRight className="w-5 h-5 ml-2" />
          </Button>
        </div>
      </div>
    </section>
  );
}